- AUTHORS
- CONTRIBUTING.md
- README.md
Solution: Add a README, AUTHORS and CONTRIBUTORS document.
> Problem: there is no information about this project

- README.md
> Problem: link to CONTRIBUTING was incorrect

- .travis.yml
Solution: add travis integration
> Problem: we have no automated testing

- channeler.go
- channeler_test.go
- zmtp.go
This PR starts the work to talk to a zeromq socket.  We are now successfully exchanging protocol signatures and versions.  Work still needs to be done to finish the handshake, and successfully send a "hello" message - which is our first end goal we are working towards.
> Problem: we cannot connect to a zeromq socket

- channeler.go
- zmtp.go
solve problem #10 
Implement zmtp v2.0 instead of version v3.0 as it is simpler to implement.
http://rfc.zeromq.org/spec:15
> Problem: zmtp handshake is not complete

- AUTHORS
> Problem: Doron is not in the authors file

- README.md
> Fix link to contributing

- README.md
- sock.go
- sock_test.go
Solution: start working on a Sock class.  Note that there is some code duplication from channeler - I'm not worried about it at the moment - just getting something working and doing some experimenting in a place where I won't break the current channeler tests.
> Problem: we want to be compatible with the net.Conn interface

- .travis.yml
- socket.go
- socket_test.go
> Problem: we need a socket api

- README.md
- socket.go
- socket_test.go
Solution: start adding support for security mechanisms
> Problem: we need security mechanism

- socket.go
- socket_test.go
Solution: start on the TCP transport implementation
> Problem: we do not speak tcp yet

- socket.go
- socket_test.go
Solution: start working on a tcp transport
> Problem: we have no transport

- socket.go
- socket_test.go
Solution: add connection retry logic so clients can be started before servers.
> Problem: connections should be stateless

- socket.go
Solution: start using the zmtp library
> Problem: we want to talk zmtp

- socket.go
> Problem: left in some debug logging

- socket.go
Solution: fix the calling code
> Problem: Prepare api call changed

- socket.go
- socket_test.go
> Problem: we cannot send a message

- socket_test.go
> Problem: tests could be better

- README.md
- socket.go
- socket_test.go
> Problem: we hate our name

- .gitignore
- AUTHORS
- socket.go
- zmtp/conn.go
- zmtp/encoding.go
- zmtp/protocol.go
- zmtp/security.go
- zmtp/security_null.go
- zmtp/security_null_test.go
- zmtp/socket.go
> Problem: It's silly to have zmtp in a seperate repo

- internal/test/externalServer.c
- internal/test/test.go
- socket_test.go
> Problem: We don't test if we can communicate with czmq

- zmtp/conn.go
- zmtp/encoding.go
- zmtp/protocol.go
Solution: Implement several fixes so we can
> Problem: We can't talk to czmq

- internal/test/externalServer.c
- internal/test/test.go
- socket_test.go
> Problem: we were not testing go to c

- socket.go
- socket_test.go
> Problem: we still did not like the name

- README.md
> Problem: README had wrong name

- zmtp/conn.go
Solution: Implement PONG replies when we get a ping
> Problem: We don't answers to pings

- socket.go
- socket_test.go
> Problem: we changed the name

- zmtp/conn.go
Solution: Change them over to gomq
> Problem: some errors don't state the new name

- .travis.yml
- socket.go
- socket_test.go
- zmtp/conn.go
- zmtp/protocol.go
Solution: begin a refactor of socket and conn to allow handling of multiple connections and multiple binds per socket.  This PR does not finish the job - it is just the first step down the road.
> Problem: we only handle single connections

- .travis.yml
- socket.go
- zmtp/conn.go
- zmtp/protocol.go
Solution: collapse things down for one channel for sending between zmtp and gomq.
> Problem: returning multiple channels to read was complicated

- zmtp/conn.go
> longLength should be 8 bytes long

- zmtp/encoding.go
- zmtp/encoding_test.go
Solution: add some tests, and remove a panic (changed to error return)
> Problem: encoding helpers did not have tests

- README.md
> Problem: README was not helpful

- socket.go
- socket_test.go
- zmtp/conn.go
- zmtp/encoding.go
- zmtp/protocol.go
- zmtp/security.go
- zmtp/security_null.go
- zmtp/socket.go
Solution: add Close to the socket interface.
> Problem: we cannot close a socket

- internal/test/test.go
- zmtp/conn.go
Solution: fix a couple of things.
> Problem: minor golint issues

- socket.go
- uuid.go
Solution: begin work on supporting multiple connections.  This PR lays some groundwork for holding multiple connections, and adding and removing connections in a goroutine safe manner.
> Problem: we do not support multiple connections

- socket.go
Solution: fix the Close routine so it doesn't deadlock :)
> Problem: Brian made a deadlock

- gomq.go
> Problem: ZeroMQSocket interface did not include RemoveConnection

- zmtp/protocol.go
> Problem: Minor grammatical error in docs

- README.md
Solution: I just installed on OSX (El Capitan)
> Problem: We didnt have docs for installing on OSX

- pull.go
- push.go
- socket_test.go
> gomq: implement Bind+Connect for PullSocket and PushSocket

- gomq.go
- socket.go
> fix: start a listener handshakes with any client that connects
